UP_FOLDER = './static/fotos'
#DB_URI = 'sqlite:///myDB.db'
DB_URI = 'mysql+pymysql://dennis:inmainma@dbtrick.ct5klwfzj701.us-east-2.rds.amazonaws.com/dbtrick'
#DB_URI = "mysql+mysqlconnector://{username}:{password}@{hostname}/{databasename}".format(
#    username="DennisDemenis",
#    password="advanced",
#    hostname="DennisDemenis.mysql.pythonanywhere-services.com",
#    databasename="DennisDemenis$cardealers",
#    )
TOKEN = "303470452:AAGorujy9KrzvNoFNZe3nVMlVY8swRxVAV8"

FILTER_WORDS = set([
    "skank",
    "wetback",
    "bitch",
    "cunt",
    "dick",
    "douchebag",
    "dyke",
    "fag",
    "nigger",
    "tranny",
    "trannies",
    "paki",
    "pussy",
    "retard",
    "slut",
    "titt",
    "tits",
    "wop",
    "whore",
    "chink",
    "fatass",
    "shemale",
    "nigga",
    "daygo",
    "dego",
    "dago",
    "gook",
    "kike",
    "kraut",
    "spic",
    "twat",
    "lesbo",
    "homo",
    "fatso",
    "lardass",
    "jap",
    "biatch",
    "tard",
    "gimp",
    "gyp",
    "chinaman",
    "chinamen",
    "golliwog",
    "crip",
    "raghead",
    "negro",
    "hooker"])
